-- Store each page's content as HTML, not stripped text.
--
-- Applied 2026-09-08, after 0008.
--
-- page_index.body_text held plain text, which made the SEO score meaningless
-- for a page: the analyser looks for subheadings, internal and external links,
-- images and lists, and stripped text contains none of those by construction.
-- Every page scored badly, no edit could improve it, and the number told the
-- editor nothing. /car-wraps/ scored 40 with nothing wrong with it.
--
-- The sections already carry real markup -- rich-text blocks ARE HTML -- so
-- the indexer now assembles a faithful HTML rendering instead of throwing the
-- structure away.
--
-- page_index is derived data, regenerated by scripts/index-pages.mjs, so it is
-- dropped and recreated rather than migrated. Nothing is lost: page_seo, which
-- holds what an editor actually set, is a separate table and is untouched.

DROP TABLE IF EXISTS page_index;

CREATE TABLE page_index (
  slug        TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  og_image    TEXT,
  words       INTEGER NOT NULL DEFAULT 0,
  -- The page as markup: headings, paragraphs, links, images and lists, so the
  -- analyser scores what the visitor actually gets.
  body_html   TEXT NOT NULL DEFAULT '',
  indexed_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
